Repository zwelhtetyan/chat-app, pull requests merged in 2023-02, with the labels that each got.

#6 implemention auth session in frontend
  frontend/src/pages/home/index.html
  frontend/src/pages/home/index.js
  frontend/src/pages/login/login.html
  frontend/src/pages/login/login.js
  frontend/src/pages/register/register.html
  frontend/src/pages/register/register.js
Labels: feat

#7 Feat/loading
  frontend/src/pages/home/index.html
  frontend/src/pages/home/index.js
  frontend/src/tailwind-output/index.css
Labels: documentation, feat

#12 Impv/scrollbar
  backend/database/users.json
  backend/index.ts
  backend/tsconfig.json
  frontend/src/pages/home/index.html
  frontend/src/pages/home/index.js
  frontend/src/styles/index.css
  frontend/src/tailwind-output/index.css
Labels: bug, impv

#9 feat:darkmode home page
  backend/controllers/userSettingController.ts
  backend/index.ts
  backend/routes/userSettingRouter.ts
  frontend/src/pages/home/index.html
  frontend/src/pages/home/index.js
  frontend/src/pages/userSetting/userSetting.html
  frontend/src/pages/userSetting/userSetting.js
  frontend/src/styles/index.css
  frontend/src/tailwind-output/index.css
  frontend/src/utils/theme.js
  frontend/tailwind.config.js
Labels: feat

#8 feat: created user setting
  backend/controllers/userSettingController.ts
  backend/database/users.json
  backend/index.ts
  backend/routes/userSettingRouter.ts
  frontend/src/pages/home/index.html
  frontend/src/pages/home/index.js
  frontend/src/pages/userSetting/userSetting.html
  frontend/src/pages/userSetting/userSetting.js
  frontend/src/styles/index.css
  frontend/src/tailwind-output/index.css
  frontend/src/utils/theme.js
  frontend/tailwind.config.js
Labels: feat

#18 Model/dynamic
  backend/controllers/loginController.ts
  backend/controllers/registerController.ts
  backend/controllers/userSettingController.ts
  backend/database/users.json
  backend/index.ts
  backend/models/history.ts
  backend/models/users.ts
  frontend/src/pages/home/index.js
Labels: bug, feat, impv

#20 bug fixed show typing
  frontend/src/pages/home/index.js
Labels: impv

#25 show active and offline No and put userImgs in activeandoffline bar
  backend/database/users.json
  backend/index.ts
  backend/models/users.ts
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/home/index.html
  frontend/src/pages/home/index.js
  frontend/src/tailwind-output/index.css
Labels: feat, impv
